### ISSUE TITLE
friends list text not appearing

### ISSUE THREAD

**Issue by Novattz** [nimsandu/spicetify-bloom#114]
The text to show what my friends names are on spotify does not appear neither what they listen to. I can click on their profile picture and it will play the song the listen to but i can directly see what they listen to. It isnt a big issue just thought i would mention it

example: [https://i.imgur.com/bVgIoEL.png](url)

**Comment by nimsandu** [comment]
this issue should be fixed with the latest spotify version

**Comment by Novattz** [comment]
still not fixed.

**Comment by Novattz** [comment]
okay so i figured out something weird. When i logged out of my account and logged into my other account on spotify it works just fine. But when i logged back in on the account i reported the issue on the text still does not appear.

**Comment by DeJayDev** [comment]
I'm seeing the same problem with

Spotify for Windows
1.1.97.962.g24733a46
Spicetify v2.14.1
Theme: Bloom / dark
Extensions: bloom.js
Custom apps: marketplace
![image](https://user-images.githubusercontent.com/19671604/198859476-8f459fdc-b749-4b0f-95f7-e31c6e7eb2e2.png)

**Comment by windowz414** [comment]
Can't reproduce this issue both on Windows and Linux.

![image](https://user-images.githubusercontent.com/39265461/208594182-0e5435c8-0ada-4dcb-9107-9c78f2ecadd8.png)

**Comment by nimsandu** [comment]
> I'm seeing the same problem with
> 
> 
> 
> Spotify for Windows
> 
> 1.1.97.962.g24733a46
> 
> Spicetify v2.14.1
> 
> Theme: Bloom / dark
> 
> Extensions: bloom.js
> 
> Custom apps: marketplace
> 
> ![image](https://user-images.githubusercontent.com/19671604/198859476-8f459fdc-b749-4b0f-95f7-e31c6e7eb2e2.png)
> 
> 


Could you try installing the theme via installation script instead and let us know
